### ISSUE TITLE
UnixStream::connect does not return a future

### ISSUE THREAD

**Issue by spinda** [tokio-rs/tokio-uds#1]
From the [documentation](https://tokio-rs.github.io/tokio-uds/tokio_uds/struct.UnixStream.html#method.connect):

> The returned future will resolve once the stream is successfully connected.

Maybe I'm misunderstanding something, but `UnixStream::connect` returns `Result<UnixStream>`, not a future.

A short example would be really helpful here.

**Comment by alexcrichton** [comment]
Thanks for the report! 

Right now this crate is intended to be very similar to `tokio_core::net`, so usage over there should translate pretty straightforwardly in terms of examples and such as well.

**Comment by spinda** [comment]
`TcpStream::connect` from `tokio_core::net` does return a future, though, which resolves when connected. Does `UnixStream::connect` block while connecting?

Also, would you accept a PR for an example snippet once I figure this all out?

**Comment by alexcrichton** [comment]
Ah yeah the `UnixStream` I believe doesn't need the future for connecting as unix sockets are connected immediately (I think, although I could be wrong). And of course yeah, I'd love to take a PR for an example!

**Comment by spinda** [comment]
I did some quick testing (on Linux) and verified that a UDS client does connect immediately even if the server never calls `accept`. However, after some more digging I found [this issue](https://github.com/nodejs/node-v0.x-archive/issues/4785#issue-11056495) from the Node.js project. They made the same assumption and were later bitten by it, as this behavior isn't guaranteed by the POSIX standard and `connect` can return `EINPROGRESS` in "some situations". It looks like the underlying `mio_uds::UnixStream` [quietly swallows](https://github.com/alexcrichton/mio-uds/blob/master/src/stream.rs#L53) this case.

**Comment by alexcrichton** [comment]
Whoa, nice investigation!

Let's leave this open in that case.

**Comment by arcnmx** [comment]
I believe I've just run into this issue, which seems to be multiple connections to a socket causing the listen queue to fill up.

```
connect(10, {sa_family=AF_UNIX, sun_path="/socket/path"}, 34) = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(3, EPOLL_CTL_ADD, 10, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4, u64=4}}) = 0
futex(0x7ffff4638198, FUTEX_WAKE_PRIVATE, 2147483647) = 1
recvfrom(10, 0x7ffff4712000, 8161, 0, NULL, NULL) = -1 EINVAL (Invalid argument)
close(10)                               = 0
```

The connect EAGAIN is ignored and then subsequent accesses to the socket end up failing later down the line :(
