### ISSUE TITLE
Sending and receiving file descriptors

### ISSUE THREAD

**Issue by maufl** [tokio-rs/tokio-uds#14]
Hi, I would like to send/receive file descriptors (unix sockets). I searched the docs but did not find anything, is it possible to do that right now?

**Comment by maufl** [comment]
Well, it looks like this isn't even supported in regular Unix sockets in rust. Therefore not supported in mio and therefore not supported in tokio.

**Comment by alexcrichton** [comment]
PRs would of course though be welcome to implement this!
