### ISSUE TITLE
Why no FromRawFd?

### ISSUE THREAD

**Issue by vi** [tokio-rs/tokio-uds#16]
How do I use pre-opened (for example by inetd) or received from another UNIX socket file descriptor in tokio-uds?

**Comment by vi** [comment]
I see there is `from_stream`, and usual UnixStream has FromRawFd. It would be easier to just provide FromRawFd.

**Comment by alexcrichton** [comment]
Thanks for the report! There's no `FromRawFd` because these types are associated with an event loop, and `FromRawFd` doesn't give the ability to pass in an event loop to associate.

**Comment by vi** [comment]
Maybe it should be mentioned in the docs then, for searching for "FromRawFd" or "from_raw_fd" not to hit nothing.

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!
