### ISSUE TITLE
Doesn't build on android target

### ISSUE THREAD

**Issue by azdlowry** [tokio-rs/tokio-uds#18]
error[E0425]: cannot find function `get_peer_cred` in module `ucred`
   --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-uds-0.1.6/src/lib.rs:288:16
    |
288 |         ucred::get_peer_cred(self)
    |                ^^^^^^^^^^^^^ not found in `ucred`

error: aborting due to previous error

**Comment by carllerche** [comment]
This should be resolved by #28.
