### ISSUE TITLE
Release new version with from_listener method

### ISSUE THREAD

**Issue by Kixunil** [tokio-rs/tokio-uds#7]
Hello, I need to use `UnixListener::from_listener()` method which is present in unreleased version of the library. Can you release 0.1.2 with that method included? If not, what is needed for release? Can I/do you need help with that?

I'm going to clone this repo for now but I'd like to use package from crates.io.

Thank you!

**Comment by alexcrichton** [comment]
Done!

**Comment by Kixunil** [comment]
Thank you very much!
